"""Add company_dev model

Revision ID: 712044114a04
Revises: cc50d79cf00b
Create Date: 2024-01-07 12:14:53.457383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712044114a04'
down_revision = 'cc50d79cf00b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_devs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_devs_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_company_devs_dev_id_devs')),
    sa.PrimaryKeyConstraint('company_id', 'dev_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_devs')
    # ### end Alembic commands ###
